"""update_audit_log_and_json_fields

Revision ID: c6a99426a8ef
Revises: c03fdf8dd0a4
Create Date: 2026-01-18 15:18:39.316722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a99426a8ef'
down_revision: Union[str, Sequence[str], None] = 'c03fdf8dd0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN. The model changes use type variants
    # and JSON types, which are compatible with existing TEXT columns for forward compatibility.
    # New databases will use the correct types.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'token_usage',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'provider_meta',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_log', 'id',
               existing_type=sa.Integer().with_variant(sa.BigInteger(), 'postgresql'),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###