"""add proxy_ip to audit_log

Revision ID: d50d2ae98169
Revises: b42d013810b3
Create Date: 2026-01-18 16:39:22.640817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50d2ae98169'
down_revision: Union[str, Sequence[str], None] = 'b42d013810b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('proxy_ip', sa.String(length=45), nullable=True))
    # Note: JSON columns in SQLite are stored as TEXT, no migration needed
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'proxy_ip')
    # Note: JSON columns in SQLite are stored as TEXT, no migration needed
    # ### end Alembic commands ###